-- DDL generated by Postico 1.5.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password text NOT NULL,
    fullname text
);

CREATE TABLE reports (
    id character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    org_name text,
    time_incident time(0) without time zone,
    date_incident date,
    org_reported text,
    issue_desc text,
    alternative text
);

CREATE TABLE languages (
    program_id character varying(100),
    language_arr text[]
);

CREATE TABLE queue (
    posted_date timestamp(0) without time zone,
    submission json,
    submission_type text,
    id text,
    status text NOT NULL
);

CREATE TABLE agencies (
    id character varying(255) PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    physical_address text NOT NULL,
    mailing_address text NOT NULL,
    disability text NOT NULL,
    phone_number text NOT NULL,
    hours text NOT NULL,
    website text NOT NULL,
    source text NOT NULL DEFAULT ''::text,
    a2s_verified boolean
);

CREATE TABLE comments (
    id character varying(255) NOT NULL,
    program_id character varying(255) NOT NULL,
    comment text,
    category character varying(100),
    submission_date timestamp(0) without time zone NOT NULL
);

CREATE TABLE programs (
    agency_id character varying(255) NOT NULL,
    id character varying(255) NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    physical_address text NOT NULL,
    ada text NOT NULL,
    application_process text NOT NULL,
    documents_required text NOT NULL,
    fee_structure text NOT NULL,
    coverage_area text NOT NULL,
    service_type text[],
    last_updated timestamp(0) without time zone,
    alternative_name text NOT NULL,
    website text NOT NULL,
    appointment_required text NOT NULL,
    accepting_clients text NOT NULL,
    transportation text NOT NULL,
    latitude numeric(10,8),
    longitude numeric(10,8),
    holiday_schedule text NOT NULL DEFAULT ''::text,
    service_area text NOT NULL DEFAULT ''::text,
    next_steps text NOT NULL DEFAULT ''::text,
    waitlist_wait text NOT NULL DEFAULT ''::text,
    other_program_enrollment text NOT NULL DEFAULT ''::text,
    other_eligibility text NOT NULL DEFAULT ''::text,
    id_accepted_notes text NOT NULL DEFAULT ''::text,
    proof_address text NOT NULL DEFAULT ''::text,
    appointment_required_notes text NOT NULL DEFAULT ''::text,
    service_available_intake text NOT NULL DEFAULT ''::text,
    service_available_intake_notes text NOT NULL DEFAULT ''::text,
    schedule_notes text NOT NULL DEFAULT ''::text,
    document_assistance text NOT NULL DEFAULT ''::text,
    visual_aids_offered text NOT NULL DEFAULT ''::text,
    consultation_opportunity text NOT NULL DEFAULT ''::text,
    enforcement_request_policy text NOT NULL DEFAULT ''::text,
    cultural_competency_offered text NOT NULL DEFAULT ''::text,
    zipcode_eligibility text[] DEFAULT '{}'::text[],
    age_eligibility text[] DEFAULT '{}'::text[],
    id_accepted_current text[] DEFAULT '{}'::text[],
    website_languages text[] DEFAULT '{}'::text[],
    frontline_languages text[] DEFAULT '{}'::text[],
    interpretation_offered text[] DEFAULT '{}'::text[],
    crisis_services_offered text[] DEFAULT '{}'::text[],
    document_languages text[] DEFAULT '{}'::text[],
    immigration_status text[] DEFAULT '{}'::text[],
    income_eligibility text NOT NULL DEFAULT ''::text,
    id_accepted_expired text[] DEFAULT '{}'::text[],
    gender_eligibility text NOT NULL DEFAULT ''::text,
    schedule json DEFAULT '{
        "monday" : [], 
        "tuesday" : [], 
        "wednesday" : [], 
        "thursday" : [], 
        "friday" : [],
        "saturday" : [], 
        "sunday" : []
    }'::json,
    service_cost text NOT NULL DEFAULT ''::text,
    source text NOT NULL DEFAULT ''::text,
    a2s_verified boolean DEFAULT false
);